#!/bin/sh
# Copy the Sphinx API doc

dest=../../API
if [ -d $dest ]; then
  rm -rf $dest
fi
cp -r API/_build/html $dest
cat > $dest/README <<EOF
This directory contains the API documentation for the package.
The documentation is automatically generated by ../src/api/make.py.
EOF
