#!/bin/sh
dest=../../odespy
cp -r sphinx-rootdir/_build/html $dest

cat > $dest/README <<EOF
This directory contains the odespy for the package.
The documentation is automatically generated by ../src/odespy/make.sh.
EOF
git add $dest
git commit -am 'Added new official odespy files.'
